# Generated by Django 2.2.10 on 2020-09-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('post', models.CharField(choices=[('coordinator', 'Coordinator'), ('co_coordinator', 'Co-Coordinator'), ('web_team', 'Web Team')], max_length=750)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('phone', models.CharField(max_length=10)),
                ('avatar', models.ImageField(upload_to='Coordinators/')),
                ('linkedIn', models.URLField(max_length=1200)),
                ('facebook', models.URLField(max_length=1200)),
                ('twitter', models.URLField(max_length=1200)),
                ('appointed_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Team Members',
            },
        ),
    ]
